export const IPC_CHANNELS = {
  openImage: 'image:open',
  exportImage: 'image:export',
  saveProject: 'project:save',
  saveProjectAtPath: 'project:save-at-path',
  openProject: 'project:open',
  openAtPath: 'file:open-at-path',
  confirmDiscardChanges: 'app:confirm-discard-changes',
  windowCloseResponse: 'window:close-response',
  menuOpenImageRequested: 'menu:open-image-requested',
  menuExportImageRequested: 'menu:export-image-requested',
  menuSaveProjectRequested: 'menu:save-project-requested',
  menuSaveProjectAsRequested: 'menu:save-project-as-requested',
  menuOpenProjectRequested: 'menu:open-project-requested',
  fileOpenRequested: 'file:open-requested',
  windowCloseRequested: 'window:close-requested',
  menuViewportAction: 'menu:viewport-action',
  menuImageAction: 'menu:image-action',
  menuHistoryAction: 'menu:history-action',
  editorStateChanged: 'editor:state-changed',
} as const;
